version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  build:
    docker:
      - image: maven:3-eclipse-temurin-11
    steps:
      - checkout
      - run:
          name: "Build"
          command: "mvn package -DskipTests"
  tests:
    docker:
      - image: maven:3-eclipse-temurin-11
    steps:
      - checkout
      - run:
          name: "Tests"
          command: "mvn test"

workflows:
  my-workflow:

    jobs:
      - say-hello
      - build:
          filters:
            branches:
              only: master
      - tests:
          filters:
            branches:
              only: master

#      - tests:
#
#          requires:
#            - build

